trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: '0e1df12c-8ec5-4f1a-b63d-44af2d1bb2cc'
  resourceGroup: 'aks_tf_rg'
  aksCluster: 'my-aks-cluster'
  imageName: 'springboot-app'
  containerRegistry: 'sagentacr130924'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      inputs:
        command: 'buildAndPush'
        repository: '$(containerRegistry)/$(imageName)'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptPath: 'deploy.sh'
        arguments: '--resource-group $(resourceGroup) --name $(aksCluster) --image $(containerRegistry)/$(imageName):$(Build.BuildId)'
